jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - 'Overall/Administer:admin'
        - 'Overall/Read:authenticated'
  remotingSecurity:
    enabled: true
  clouds:
    - docker:
        dockerApi:
          connectTimeout: 60
          dockerHost:
            uri: 'tcp://host.docker.internal:2375'
          readTimeout: 60
        name: 'docker'

jobs:
  - file: ./jobdsl/001-bootstrap.groovy
  - file: ./jobdsl/002-test-agent.groovy

unclassified:
  location:
    url: ${JENKINS_URL}
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: 'https://tobix.github.io/jenkins-neo2-theme/dist/neo-light.css'
