pipeline {
  agent { label 'agent-001' }
  environment {
    CI = 'true'
  }
  stages {
    stage('Prepare') {
      steps {
        sh 'npm install'
      }
    }
    stage('Test') {
      steps {
        sh 'npm test'
      }
    }
  }
}
